### ISSUE TITLE
Weird number-only-rows in result set

### ISSUE THREAD

**Issue by larsparendt** [sqlitecloud/sqlitecloud-swift#3]
I'm not able to fetch a proper result set. I get a mix of numbers and text.

My setup:

Doing this in `didFinishLaunchingWithOptions`:

```
        Task {
            guard let configuration = SQLiteCloudConfig(connectionString: "sqlitecloud://admin:xxxxxxxx@xxxxxxxx.sqlite.cloud:8860/chinook.sqlite") else {
                return
            }

            let sqliteCloud = SQLiteCloud(config: configuration)

            do {
                try await sqliteCloud.connect()
                debuPrint("connected")
                AppDelegate.sqlite = sqliteCloud
            } catch {
                debugPrint("connection error: \(error)") // SQLiteCloudConnectionError
            }
        }
```

and connect successfully.

Then I perform a fetch, like this:

```
            let res = try? await AppDelegate.sqlite.execute(query: "SELECT * FROM 'albums' where AlbumId = 9") 
            self.textView.text = res?.stringValue
```

and get this:

```
SQLiteCloudRowset(columns: ["AlbumId", "Title", "ArtistId"], rows: [[1, 1, 1]])
```

If I skip the where clause and and use `limit 5` I get this:

```
SQLiteCloudRowset(columns: ["AlbumId", "Title", "ArtistId"], rows: [[1, 1, 1], [1, 0, 0], [1, 0, 0], [1, For Those About To Rock We Salute You1, 1], [2, Balls to the Wall2, 2]])
```

What are those all-numbers-rows in the start of the result set doing there?

Am I missing something?

thanks,
Lars

**Comment by marcobambini** [comment]
@larsparendt this issue is related to https://github.com/sqlitecloud/sqlitecloud-kotlin
We should update the underlying C SDK pretty soon

**Comment by marcobambini** [comment]
@larsparendt xcframeworks just updated. Can you please confirm that it now works as expected?

**Comment by larsparendt** [comment]
@marcobambini thanks a lot - it works as intended. Very cool.
